name: BuildDebianPackage

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build_debian_package:
    name: BuildDebianPackage
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        rosdistro : [foxy,galactic]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: OUXT-Polaris/ouxt_distro
          token: ${{ secrets.WAMV_TAN_BOT_SECRET }}
          path: "ouxt_distro"
      - name: Setup ROS2 ${{ matrix.rosdistro }} environment
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: ${{ matrix.rosdistro }}
      - name: add to rosdep.yaml
        run: "yaml file:///$GITHUB_WORKSPACE/ouxt_distro/rosdep.yaml >> /etc/ros/rosdep/sources.list.d/20-default.list"
      - name: rosdep update
        run: rosdep update