name: BuildTest

on:
  schedule:
    - cron: 0 0 * * *
  pull_request:
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        rosdistro : [foxy,galactic]
    steps:
      - uses: actions/checkout@v2-beta
      - name: Check dependency-${{ matrix.rosdistro }}.repos existence
        id: check_rosdistro_repos_files
        uses: andstor/file-existence-action@v1
        with:
          files: dependency-${{ matrix.rosdistro }}.repos
          allow_failure: false
      - name: Check dependency.repos existence
        id: check_repos_files
        uses: andstor/file-existence-action@v1
        with:
          files: dependency.repos
          allow_failure: false
      - name: Run ichiro-its/ros2-ci@v1.0.0 with dependency-${{ matrix.rosdistro }}.repos
        uses: ichiro-its/ros2-ci@v1.0.0
        if: steps.check_rosdistro_repos_files.outputs.files_exists == 'true'
        with:
          ros2-distro: ${{ matrix.rosdistro }}
          external-repos: dependency-${{ matrix.rosdistro }}.repos
      - name: Run ichiro-its/ros2-ci@v1.0.0 with dependency.repos
        uses: ichiro-its/ros2-ci@v1.0.0
        if: steps.check_rosdistro_repos_files.outputs.files_exists == 'false' && steps.check_repos_files.outputs.files_exists == 'true'
        with:
          ros2-distro: ${{ matrix.rosdistro }}
          external-repos: dependency.repos
      - name: Run ichiro-its/ros2-ci@v1.0.0 without repos
        uses: ichiro-its/ros2-ci@v1.0.0
        if: steps.check_rosdistro_repos_files.outputs.files_exists == 'false' && steps.check_repos_files.outputs.files_exists == 'false'
        with:
          ros2-distro: ${{ matrix.rosdistro }}
      - name: Notify Slack
        uses: 8398a7/action-slack@v2
        if: failure()
        with:
          status: ${{ job.status }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}