name: BuildDebianPackage

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  fetch_rosdep_yaml:
    name: Fetch rosdep.yaml
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          repository: OUXT-Polaris/ouxt_distro
          token: ${{ secrets.WAMV_TAN_BOT_SECRET }}
      - uses: actions/upload-artifact@v2
        with:
          name: rosdep_yaml
          path: rosdep.yaml

  build_debian_package:
    name: Build debian package
    runs-on: ubuntu-20.04
    needs: fetch_rosdep_yaml
    strategy:
      fail-fast: false
      matrix:
        rosdistro : [foxy,galactic]
    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ github.repository.name }}
      - uses: actions/download-artifact@v2
        with:
          name: rosdep_yaml
      - name: check rosdep_yaml
        run: cat rosdep.yaml
      - name: Check dependency-${{ matrix.rosdistro }}.repos existence
        id: check_rosdistro_repos_files
        uses: andstor/file-existence-action@v1
        with:
          files: dependency-${{ matrix.rosdistro }}.repos
          allow_failure: false
      - name: Check dependency.repos existence
        id: check_repos_files
        uses: andstor/file-existence-action@v1
        with:
          files: dependency.repos
          allow_failure: false
      - name: Setup ROS2 ${{ matrix.rosdistro }} environment
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: ${{ matrix.rosdistro }}
      - name: add to rosdep.yaml
        run: echo 'yaml file:///home/runner/work/ouxt_common/ouxt_common/rosdep.yaml' | sudo tee -a /etc/ros/rosdep/sources.list.d/20-default.list
      - name: rosdep update
        run: rosdep update
      - name: Run ros-tooling/action-ros-ci@v0.2 with dependency-${{ matrix.rosdistro }}.repos
        uses: ros-tooling/action-ros-ci@v0.2
        if: steps.check_rosdistro_repos_files.outputs.files_exists == 'true'
        with:
          package-name: ${{ steps.list_packages.outputs.package_list }}
          target-ros2-distro: ${{ matrix.rosdistro }}
          colcon-defaults: |
            {
              "build": {
                "mixin": ["coverage-gcc"]
              }
            }
          # If possible, pin the repository in the workflow to a specific commit to avoid
          # changes in colcon-mixin-repository from breaking your tests.
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/1ddb69bedfd1f04c2f000e95452f7c24a4d6176b/index.yaml
          vcs-repo-file-url: dependency-${{ matrix.rosdistro }}.repos
      - name: Run ros-tooling/action-ros-ci@v0.2 with dependency.repos
        uses: ros-tooling/action-ros-ci@v0.2
        if: steps.check_rosdistro_repos_files.outputs.files_exists == 'false' && steps.check_repos_files.outputs.files_exists == 'true'
        with:
          package-name: ${{ steps.list_packages.outputs.package_list }}
          target-ros2-distro: ${{ matrix.rosdistro }}
          colcon-defaults: |
            {
              "build": {
                "mixin": ["coverage-gcc"]
              }
            }
          # If possible, pin the repository in the workflow to a specific commit to avoid
          # changes in colcon-mixin-repository from breaking your tests.
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/1ddb69bedfd1f04c2f000e95452f7c24a4d6176b/index.yaml
          vcs-repo-file-url: dependency.repos
      - name: Run ros-tooling/action-ros-ci@v0.2 without repos
        uses: ros-tooling/action-ros-ci@v0.2
        if: steps.check_rosdistro_repos_files.outputs.files_exists == 'false' && steps.check_repos_files.outputs.files_exists == 'false'
        with:
          package-name: ${{ steps.list_packages.outputs.package_list }}
          target-ros2-distro: ${{ matrix.rosdistro }}
          colcon-defaults: |
            {
              "build": {
                "mixin": ["coverage-gcc"]
              }
            }
          # If possible, pin the repository in the workflow to a specific commit to avoid
          # changes in colcon-mixin-repository from breaking your tests.
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/1ddb69bedfd1f04c2f000e95452f7c24a4d6176b/index.yaml
      - name: generate debian package
        run: colcon list --names-only | xargs -L 1 bash -c 'cd "$0" && bloom-generate rosdebian --os-version focal --ros-distro ${{ matrix.rosdistro }} && fakeroot debian/rules binary'
      - name: Notify Slack
        uses: 8398a7/action-slack@v2
        if: failure()
        with:
          status: ${{ job.status }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}