name: PrepareRelease

on:
  issues:
    types: [opened]


jobs:
  Release:
    name: Release ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: create release
        id: create_release
        uses: at-wat/catkin-release-action@v1
        with:
          issue_title: ${{ github.event.issue.title }}
          git_user: wam-v-tan
          git_email: ouxt.share@gmail.com
          github_token: ${{ secrets.WAMV_TAN_BOT_SECRET }}
      - name: open pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ steps.create_release.outputs.created_branch }}
          destination_branch: ${{ github.event.repository.default_branch }}
          pr_title: Release ${{ steps.create_release.outputs.version}}
          pr_body: close \#${{ github.event.issue.number }}
          pr_assignee: ${{ github.actor }}
          github_token: ${{ secrets.GITHUB_TOKEN }}