name: Release

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'version'
        required: true

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: create release
        id: create_release
        uses: at-wat/catkin-release-action@v1
        with:
          git_user: wam-v-tan
          git_email: ouxt.share@gmail.com
          github_token: ${{ secrets.WAMV_TAN_BOT_SECRET }}
          version: ${{ github.event.inputs.version }}
      - uses: peter-evans/create-pull-request@v3
        id: create_pull_request
        if: steps.check_branch.outputs.exist == 0 && steps.changes.outputs.count > 0
        with:
          token: ${{ secrets.WAMV_TAN_BOT_SECRET }}
          commit-message: Release version ${{ github.event.inputs.version }}
          committer: wam-v-tan <ouxt.share@gmail.com>
          author: wam-v-tan <ouxt.share@gmail.com>
          signoff: false
          branch: release/${{ github.event.inputs.version }}
          base: ${{ steps.check_default_branch.outputs.default_branch }}
          delete-branch: true
          title: '[Bot] Release ${{ github.event.inputs.version }}'
          body: |
            # Description
            Release version ${{ github.event.inputs.version }}
            # How to check
            Please check passing all CI test.
          labels: |
            bot
          assignees: wam-v-tan
          reviewers: wam-v-tan
          team-reviewers: |
            owners
            maintainers
          draft: false