name: PrepareRelease

on:
  issues:
    types: [opened]

jobs:
  Release:
    name: Prepare Release ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: create release
        id: create_release
        uses: at-wat/catkin-release-action@v1
        with:
          issue_title: ${{ github.event.issue.title }}
          git_user: wam-v-tan
          git_email: ouxt.share@gmail.com
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: repo-sync/pull-request@v2
        id: create_pull_request
        with:
          source_branch: ${{ steps.create_release.outputs.created_branch }}
          destination_branch: master
          pr_title: Release ${{ steps.create_release.outputs.version}}
          pr_body: close \#${{ github.event.issue.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable Pull Request Automerge
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.WAMV_TAN_BOT_SECRET }}
          pull-request-number: ${{ steps.create_pull_request.outputs.pr_number }}
          merge-method: squash
          repository: ${{ github.repository }}