name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true

jobs:
  Release:
    name: Release ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: install bloom
        run: |
          pip3 install bloom
      - uses: EndBug/add-and-commit@v7
        with:
          author_name: wam-v-tan
          author_email: ouxt.share@gmail.com
          message: 'Update changelog for ${{ github.event.inputs.version }}'
          add: '--all'
      - name: generate changelog
        run: |
          catkin_generate_changelog
      - name: prepare release with specific version
        run: |
          catkin_prepare_release --version ${{ github.event.inputs.version }} -y