name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true

jobs:
  Release:
    name: Release ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: |
          git clone ${{ github.server_url }}/${{ github.repository }}.git
      - name: ls
        run: ls
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: install bloom
        run: |
          pip3 install bloom
      - name: prepare git config
        run: |
          git config --global user.email "ouxt.share@gmail.com"
          git config --global user.name "wam-v-tan"
      - name: generate changelog
        run: |
          catkin_generate_changelog
      - name: prepare release with specific version
        run: |
          catkin_prepare_release --version ${{ github.event.inputs.version }} -y