name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true

jobs:
  Release:
    name: Release ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: install bloom
        run: |
          pip3 install bloom
      - name: generate changelog
        run: |
          catkin_generate_changelog
      - uses: peter-evans/create-pull-request@v3
        id: create_pull_request
        with:
          token: ${{ secrets.WAMV_TAN_BOT_SECRET }}
          commit-message: Release ${{ github.event.inputs.version }}
          committer: wam-v-tan <ouxt.share@gmail.com>
          author: wam-v-tan <ouxt.share@gmail.com>
          signoff: false
          branch: release/${{ github.event.inputs.version }}
          base: ${{ steps.check_default_branch.outputs.default_branch }}
          delete-branch: true
          title: '[Bot] Update workflow'
          body: |
            # Description  
            Release ${{ github.event.inputs.version }}  
          labels: |
            bot
          assignees: wam-v-tan
          reviewers: wam-v-tan
          team-reviewers: |
            owners
            maintainers
          draft: false
      - name: Enable Pull Request Automerge
        if: steps.create_pull_request.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.WAMV_TAN_BOT_SECRET }}
          pull-request-number: ${{ steps.create_pull_request.outputs.pull-request-number }}
          merge-method: squash
          repository: ${{ github.repository }}
      - name: prepare release with specific version
        run: |
          catkin_prepare_release --version ${{ github.event.inputs.version }} -y