name: Release

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'version'
        required: true

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: install bloom
        run: |
          pip3 install bloom
      - name: generate changelog
        run: |
          catkin_generate_changelog
        continue-on-error: true
      - name: prepare release
        run: |
          catkin_prepare_release --version ${{ github.event.inputs.version }} -y
