name: PrepareRelease

on:
  issues:
    types: [opened]


jobs:
  Release:
    name: Release ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: create release
        id: create_release
        uses: at-wat/catkin-release-action@v1
        with:
          issue_title: ${{ github.event.issue.title }}
          git_user: wam-v-tan
          git_email: ouxt.share@gmail.com
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.WAMV_TAN_BOT_SECRET }}
          commit-message: Release ${{ github.event.inputs.version }}
          committer: wam-v-tan <ouxt.share@gmail.com>
          author: wam-v-tan <ouxt.share@gmail.com>
          signoff: false
          branch: ${{ steps.create_release.outputs.created_branch }}
          base: ${{ github.event.repository.default_branch }}
          delete-branch: true
          title: '[Bot] Update workflow'
          body: |
            # Description  
            Release ${{ github.event.inputs.version }}  
            close \#${{ github.event.issue.number }}  
          labels: |
            bot
          assignees: wam-v-tan
          reviewers: wam-v-tan
          team-reviewers: |
            owners
            maintainers
          draft: false
      - name: Enable Pull Request Automerge
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.WAMV_TAN_BOT_SECRET }}
          pull-request-number: ${{ steps.create_pull_request.outputs.pull-request-number }}
          merge-method: squash
          repository: OUXT-Polaris/${{ matrix.package_name }}