name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true

jobs:
  Release:
    name: Release ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: install bloom
        run: |
          pip3 install bloom
      - name: generate changelog
        run: |
          catkin_generate_changelog
      - name: prepare git config
        run: |
          git config --global user.email "ouxt.share@gmail.com"
          git config --global user.name "wam-v-tan"
      - name: commit changes
        run: |
          git checkout -b release/${{ github.event.inputs.version }}
          git add --all
          git commit -m "release version ${{ github.event.inputs.version }}"
      - name: prepare release with specific version
        run: |
          catkin_prepare_release --version ${{ github.event.inputs.version }} -y
      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.WAMV_TAN_BOT_SECRET }}
          commit-message: Setup workflow
          committer: wam-v-tan <ouxt.share@gmail.com>
          author: wam-v-tan <ouxt.share@gmail.com>
          signoff: false
          branch: release/${{ github.event.inputs.version }}
          base: ${{ github.event.repository.default_branch }}
          delete-branch: true
          title: '[Bot] Release ${{ github.event.inputs.version }}'
          body: |
            # Description
            Release ${{ github.event.inputs.version }}
            # How to check
            Please check passing all CI test.
          labels: |
            bot
          assignees: wam-v-tan
          reviewers: wam-v-tan
          team-reviewers: |
            owners
            maintainers
          draft: false